const MOVIES = [
  { title: "Sholay", year: 1975, language: "bollywood", difficulty: "easy" },
  { title: "Dilwale Dulhania Le Jayenge", year: 1995, language: "bollywood", difficulty: "easy" },
  { title: "3 Idiots", year: 2009, language: "bollywood", difficulty: "easy" },
  { title: "Lagaan", year: 2001, language: "bollywood", difficulty: "easy" },
  { title: "Dangal", year: 2016, language: "bollywood", difficulty: "easy" },
  { title: "PK", year: 2014, language: "bollywood", difficulty: "easy" },
  { title: "Bajrangi Bhaijaan", year: 2015, language: "bollywood", difficulty: "easy" },
  { title: "Kuch Kuch Hota Hai", year: 1998, language: "bollywood", difficulty: "easy" },
  { title: "Kabhi Khushi Kabhie Gham", year: 2001, language: "bollywood", difficulty: "easy" },
  { title: "Zindagi Na Milegi Dobara", year: 2011, language: "bollywood", difficulty: "easy" },
  { title: "Jab We Met", year: 2007, language: "bollywood", difficulty: "easy" },
  { title: "Rang De Basanti", year: 2006, language: "bollywood", difficulty: "easy" },
  { title: "Dil Chahta Hai", year: 2001, language: "bollywood", difficulty: "easy" },
  { title: "Munna Bhai M.B.B.S.", year: 2003, language: "bollywood", difficulty: "easy" },
  { title: "Hum Aapke Hain Koun", year: 1994, language: "bollywood", difficulty: "easy" },
  { title: "Dhoom", year: 2004, language: "bollywood", difficulty: "easy" },
  { title: "Don", year: 2006, language: "bollywood", difficulty: "easy" },
  { title: "Krrish", year: 2006, language: "bollywood", difficulty: "easy" },
  { title: "Sultan", year: 2016, language: "bollywood", difficulty: "easy" },
  { title: "Dabangg", year: 2010, language: "bollywood", difficulty: "easy" },
  { title: "Chennai Express", year: 2013, language: "bollywood", difficulty: "easy" },
  { title: "Padmaavat", year: 2018, language: "bollywood", difficulty: "easy" },
  { title: "War", year: 2019, language: "bollywood", difficulty: "easy" },
  { title: "Baahubali", year: 2015, language: "bollywood", difficulty: "easy" },
  { title: "Singham", year: 2011, language: "bollywood", difficulty: "easy" },
  { title: "Golmaal", year: 2006, language: "bollywood", difficulty: "easy" },
  { title: "Hera Pheri", year: 2000, language: "bollywood", difficulty: "easy" },
  { title: "Drishyam", year: 2015, language: "bollywood", difficulty: "easy" },
  { title: "Stree", year: 2018, language: "bollywood", difficulty: "easy" },
  { title: "Andhadhun", year: 2018, language: "bollywood", difficulty: "easy" },
  { title: "Gully Boy", year: 2019, language: "bollywood", difficulty: "easy" },
  { title: "Chhichhore", year: 2019, language: "bollywood", difficulty: "easy" },
  { title: "Tanhaji", year: 2020, language: "bollywood", difficulty: "easy" },
  { title: "Pathaan", year: 2023, language: "bollywood", difficulty: "easy" },
  { title: "Jawan", year: 2023, language: "bollywood", difficulty: "easy" },
  { title: "Animal", year: 2023, language: "bollywood", difficulty: "easy" },
  { title: "Gangs of Wasseypur", year: 2012, language: "bollywood", difficulty: "medium" },
  { title: "Barfi!", year: 2012, language: "bollywood", difficulty: "medium" },
  { title: "Queen", year: 2014, language: "bollywood", difficulty: "medium" },
  { title: "Raees", year: 2017, language: "bollywood", difficulty: "medium" },
  { title: "Kick", year: 2014, language: "bollywood", difficulty: "medium" },
  { title: "Fan", year: 2016, language: "bollywood", difficulty: "medium" },
  { title: "Tamasha", year: 2015, language: "bollywood", difficulty: "medium" },
  { title: "Rockstar", year: 2011, language: "bollywood", difficulty: "medium" },
  { title: "Devdas", year: 2002, language: "bollywood", difficulty: "medium" },
  { title: "Black", year: 2005, language: "bollywood", difficulty: "medium" },
  { title: "Swades", year: 2004, language: "bollywood", difficulty: "medium" },
  { title: "Taare Zameen Par", year: 2007, language: "bollywood", difficulty: "medium" },
  { title: "Raanjhanaa", year: 2013, language: "bollywood", difficulty: "medium" },
  { title: "Lootera", year: 2013, language: "bollywood", difficulty: "medium" },
  { title: "Haider", year: 2014, language: "bollywood", difficulty: "medium" },
  { title: "Udta Punjab", year: 2016, language: "bollywood", difficulty: "medium" },
  { title: "Toilet: Ek Prem Katha", year: 2017, language: "bollywood", difficulty: "medium" },
  { title: "Badhaai Ho", year: 2018, language: "bollywood", difficulty: "medium" },
  { title: "Luka Chuppi", year: 2019, language: "bollywood", difficulty: "medium" },
  { title: "Bala", year: 2019, language: "bollywood", difficulty: "medium" },
  { title: "Panga", year: 2020, language: "bollywood", difficulty: "medium" },
  { title: "Thappad", year: 2020, language: "bollywood", difficulty: "medium" },
  { title: "Shershaah", year: 2021, language: "bollywood", difficulty: "medium" },
  { title: "Laal Singh Chaddha", year: 2022, language: "bollywood", difficulty: "medium" },
  { title: "Gehraiyaan", year: 2022, language: "bollywood", difficulty: "medium" },
  { title: "Darr", year: 1993, language: "bollywood", difficulty: "medium" },
  { title: "Baazigar", year: 1993, language: "bollywood", difficulty: "medium" },
  { title: "Dil", year: 1990, language: "bollywood", difficulty: "medium" },
  { title: "Qayamat Se Qayamat Tak", year: 1988, language: "bollywood", difficulty: "medium" },
  { title: "Maine Pyar Kiya", year: 1989, language: "bollywood", difficulty: "medium" },
  { title: "Ghajini", year: 2008, language: "bollywood", difficulty: "medium" },
  { title: "Om Shanti Om", year: 2007, language: "bollywood", difficulty: "medium" },
  { title: "Rab Ne Bana Di Jodi", year: 2008, language: "bollywood", difficulty: "medium" },
  { title: "Band Baaja Baaraat", year: 2010, language: "bollywood", difficulty: "medium" },
  { title: "Yeh Jawaani Hai Deewani", year: 2013, language: "bollywood", difficulty: "medium" },
  { title: "Piku", year: 2015, language: "bollywood", difficulty: "medium" },
  { title: "Maqbool", year: 2003, language: "bollywood", difficulty: "hard" },
  { title: "Omkara", year: 2006, language: "bollywood", difficulty: "hard" },
  { title: "Gulaal", year: 2009, language: "bollywood", difficulty: "hard" },
  { title: "Aamir", year: 2008, language: "bollywood", difficulty: "hard" },
  { title: "Satya", year: 1998, language: "bollywood", difficulty: "hard" },
  { title: "Company", year: 2002, language: "bollywood", difficulty: "hard" },
  { title: "Dil Se", year: 1998, language: "bollywood", difficulty: "hard" },
  { title: "Bombay", year: 1995, language: "bollywood", difficulty: "hard" },
  { title: "Roja", year: 1992, language: "bollywood", difficulty: "hard" },
  { title: "Hazaaron Khwaishein Aisi", year: 2005, language: "bollywood", difficulty: "hard" },
  { title: "Oye Lucky! Lucky Oye!", year: 2008, language: "bollywood", difficulty: "hard" },
  { title: "Dev.D", year: 2009, language: "bollywood", difficulty: "hard" },
  { title: "Peepli Live", year: 2010, language: "bollywood", difficulty: "hard" },
  { title: "Shanghai", year: 2012, language: "bollywood", difficulty: "hard" },
  { title: "Ugly", year: 2013, language: "bollywood", difficulty: "hard" },
  { title: "Titli", year: 2014, language: "bollywood", difficulty: "hard" },
  { title: "Masaan", year: 2015, language: "bollywood", difficulty: "hard" },
  { title: "Trapped", year: 2016, language: "bollywood", difficulty: "hard" },
  { title: "Tumbbad", year: 2018, language: "bollywood", difficulty: "hard" },
  { title: "Mukkabaaz", year: 2018, language: "bollywood", difficulty: "hard" },
  { title: "Gurgaon", year: 2017, language: "bollywood", difficulty: "hard" },
  { title: "Raman Raghav 2.0", year: 2016, language: "bollywood", difficulty: "hard" },
  { title: "Paan Singh Tomar", year: 2012, language: "bollywood", difficulty: "hard" },
  { title: "Kahaani", year: 2012, language: "bollywood", difficulty: "hard" },
  { title: "Talvar", year: 2015, language: "bollywood", difficulty: "hard" },
  { title: "Badla", year: 2019, language: "bollywood", difficulty: "hard" },
  { title: "Article 15", year: 2019, language: "bollywood", difficulty: "hard" },
  { title: "Chhapaak", year: 2020, language: "bollywood", difficulty: "hard" },
  { title: "Andheri Raat Mein Diya", year: 1967, language: "bollywood", difficulty: "hard" },
  { title: "Pyaasa", year: 1957, language: "bollywood", difficulty: "hard" },
  { title: "Mughal-e-Azam", year: 1960, language: "bollywood", difficulty: "hard" },
  { title: "Guide", year: 1965, language: "bollywood", difficulty: "hard" },
  { title: "Mother India", year: 1957, language: "bollywood", difficulty: "hard" },
  { title: "Titanic", year: 1997, language: "hollywood", difficulty: "easy" },
  { title: "The Avengers", year: 2012, language: "hollywood", difficulty: "easy" },
  { title: "Spider-Man", year: 2002, language: "hollywood", difficulty: "easy" },
  { title: "The Lion King", year: 1994, language: "hollywood", difficulty: "easy" },
  { title: "Jurassic Park", year: 1993, language: "hollywood", difficulty: "easy" },
  { title: "Harry Potter", year: 2001, language: "hollywood", difficulty: "easy" },
  { title: "Frozen", year: 2013, language: "hollywood", difficulty: "easy" },
  { title: "Fast & Furious", year: 2001, language: "hollywood", difficulty: "easy" },
  { title: "Iron Man", year: 2008, language: "hollywood", difficulty: "easy" },
  { title: "Batman", year: 2005, language: "hollywood", difficulty: "easy" },
  { title: "Superman", year: 1978, language: "hollywood", difficulty: "easy" },
  { title: "Kung Fu Panda", year: 2008, language: "hollywood", difficulty: "easy" },
  { title: "Finding Nemo", year: 2003, language: "hollywood", difficulty: "easy" },
  { title: "Toy Story", year: 1995, language: "hollywood", difficulty: "easy" },
  { title: "The Matrix", year: 1999, language: "hollywood", difficulty: "easy" },
  { title: "Inception", year: 2010, language: "hollywood", difficulty: "easy" },
  { title: "Avatar", year: 2009, language: "hollywood", difficulty: "easy" },
  { title: "Joker", year: 2019, language: "hollywood", difficulty: "easy" },
  { title: "Deadpool", year: 2016, language: "hollywood", difficulty: "easy" },
  { title: "Top Gun", year: 1986, language: "hollywood", difficulty: "easy" },
  { title: "Terminator", year: 1984, language: "hollywood", difficulty: "easy" },
  { title: "Rocky", year: 1976, language: "hollywood", difficulty: "easy" },
  { title: "Mission: Impossible", year: 1996, language: "hollywood", difficulty: "easy" },
  { title: "Pirates of the Caribbean", year: 2003, language: "hollywood", difficulty: "easy" },
  { title: "Transformers", year: 2007, language: "hollywood", difficulty: "easy" },
  { title: "The Dark Knight", year: 2008, language: "hollywood", difficulty: "medium" },
  { title: "Interstellar", year: 2014, language: "hollywood", difficulty: "medium" },
  { title: "The Shawshank Redemption", year: 1994, language: "hollywood", difficulty: "medium" },
  { title: "Forrest Gump", year: 1994, language: "hollywood", difficulty: "medium" },
  { title: "Gladiator", year: 2000, language: "hollywood", difficulty: "medium" },
  { title: "The Godfather", year: 1972, language: "hollywood", difficulty: "medium" },
  { title: "Fight Club", year: 1999, language: "hollywood", difficulty: "medium" },
  { title: "Pulp Fiction", year: 1994, language: "hollywood", difficulty: "medium" },
  { title: "Shutter Island", year: 2010, language: "hollywood", difficulty: "medium" },
  { title: "The Wolf of Wall Street", year: 2013, language: "hollywood", difficulty: "medium" },
  { title: "Django Unchained", year: 2012, language: "hollywood", difficulty: "medium" },
  { title: "The Prestige", year: 2006, language: "hollywood", difficulty: "medium" },
  { title: "John Wick", year: 2014, language: "hollywood", difficulty: "medium" },
  { title: "Mad Max: Fury Road", year: 2015, language: "hollywood", difficulty: "medium" },
  { title: "Gravity", year: 2013, language: "hollywood", difficulty: "medium" },
  { title: "The Revenant", year: 2015, language: "hollywood", difficulty: "medium" },
  { title: "Black Panther", year: 2018, language: "hollywood", difficulty: "medium" },
  { title: "A Quiet Place", year: 2018, language: "hollywood", difficulty: "medium" },
  { title: "Parasite", year: 2019, language: "hollywood", difficulty: "medium" },
  { title: "Dune", year: 2021, language: "hollywood", difficulty: "medium" },
  { title: "Everything Everywhere All at Once", year: 2022, language: "hollywood", difficulty: "medium" },
  { title: "Oppenheimer", year: 2023, language: "hollywood", difficulty: "medium" },
  { title: "Memento", year: 2000, language: "hollywood", difficulty: "hard" },
  { title: "Mulholland Drive", year: 2001, language: "hollywood", difficulty: "hard" },
  { title: "Requiem for a Dream", year: 2000, language: "hollywood", difficulty: "hard" },
  { title: "Eternal Sunshine of the Spotless Mind", year: 2004, language: "hollywood", difficulty: "hard" },
  { title: "No Country for Old Men", year: 2007, language: "hollywood", difficulty: "hard" },
  { title: "There Will Be Blood", year: 2007, language: "hollywood", difficulty: "hard" },
  { title: "Birdman", year: 2014, language: "hollywood", difficulty: "hard" },
  { title: "Whiplash", year: 2014, language: "hollywood", difficulty: "hard" },
  { title: "The Grand Budapest Hotel", year: 2014, language: "hollywood", difficulty: "hard" },
  { title: "Moonlight", year: 2016, language: "hollywood", difficulty: "hard" },
  { title: "Arrival", year: 2016, language: "hollywood", difficulty: "hard" },
  { title: "The Lighthouse", year: 2019, language: "hollywood", difficulty: "hard" },
  { title: "Midsommar", year: 2019, language: "hollywood", difficulty: "hard" },
  { title: "The Witch", year: 2015, language: "hollywood", difficulty: "hard" },
  { title: "Ex Machina", year: 2014, language: "hollywood", difficulty: "hard" },
  { title: "Drive", year: 2011, language: "hollywood", difficulty: "hard" },
  { title: "Nightcrawler", year: 2014, language: "hollywood", difficulty: "hard" },
  { title: "Prisoners", year: 2013, language: "hollywood", difficulty: "hard" },
  { title: "Sicario", year: 2015, language: "hollywood", difficulty: "hard" },
  { title: "Wind River", year: 2017, language: "hollywood", difficulty: "hard" },
  { title: "Blade Runner 2049", year: 2017, language: "hollywood", difficulty: "hard" },
  { title: "The Killing of a Sacred Deer", year: 2017, language: "hollywood", difficulty: "hard" },
  { title: "Hereditary", year: 2018, language: "hollywood", difficulty: "hard" },
  { title: "Annihilation", year: 2018, language: "hollywood", difficulty: "hard" },
  { title: "The Favourite", year: 2018, language: "hollywood", difficulty: "hard" },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = MOVIES;
} else {
  window.MOVIES = MOVIES;
}
